fix: rename "Whitelist" to "Allow list"
alphagov/govwifi-admin pull request #1200
Opened 2020-12-01 15:30 UTC by freesteph

2020-12-01 15:32 UTC, bethwalton commented on app/views/super_admin/whitelists/email_domains/_confirm_remove_email_domain.html.erb
> +    <%= button_to "Yes, remove #{params[:domain_to_remove]} from the allowed list", super_admin_whitelist_email_domain_path(params[:id]), method: :delete, class: "govuk-button red-button" %>
Think this should be "allow list"?

2020-12-01 15:38 UTC, bethwalton reviewed
Just those changes of "allowed list" to "allow list". 

Everything else looks great, thank you! :D

2020-12-01 15:38 UTC, bethwalton commented on spec/features/super_admin/whitelists/authorised_email_domain_spec.rb
> +        expect { click_on "Yes, remove #{some_domain} from the allowed list" }.to change(AuthorisedEmailDomain, :count).by(-1)
Can these ones all be 'allow list' too?

2020-12-01 15:38 UTC, alan-gds requested changes
I've not done a full review yet, but I did a quick search to see if any user-facing text was missed and found a couple of cases; it'd be worth fixing these while I continue to look at the changes that have been made so far.

```
app/models/organisation.rb
25:      errors.add(:base, "#{name} isn't a whitelisted organisation")
```

```
app/views/help/user_support.html.erb
10:    <p class="govuk-body">Contact us for help and support with users connecting to GovWifi in your organisation. We can assist with user log information and whitelisting public sector email domains.</p>
```

2020-12-02 09:11 UTC, freesteph commented
> I've not done a full review, but I did a quick search to see if any user-facing text was missed and found a couple of cases.
> 
> ```
> app/models/organisation.rb
> 25:      errors.add(:base, "#{name} isn't a whitelisted organisation")
> ```

Updated, thanks.

> 
> ```
> app/views/help/user_support.html.erb
> 10:    <p class="govuk-body">Contact us for help and support with users connecting to GovWifi in your organisation. We can assist with user log information and whitelisting public sector email domains.</p>
> ```

Discussed with @bethwalton; sentence deemed vague so altogether removed.

:heavy_check_mark:

2020-12-02 10:08 UTC, bethwalton approved these changes

2020-12-02 10:21 UTC, alan-gds approved these changes
Looks good to me.  Would be nice to change internal mentions of whitelist in the code and in various paths at some point (for consistency), but this PR covers the more urgent job of dealing with all the content that's visible on actual pages.

2020-12-02 10:31 UTC, merged