Remove option to skip 2FA
alphagov/govwifi-admin pull request #1337
Opened 2021-07-22 16:13 UTC by colinbm

### What

* Remove the skip 2FA link
* Remove the linked page
* Remove the skip logic
* Update page design, including text based key

### Why

We now require 2FA

Link to Trello card (if applicable): https://trello.com/c/yAmMqzjT

2021-07-22 16:15 UTC, sarahseewhy approved these changes

2021-07-23 09:24 UTC, koetsier requested changes
Could you split this up into 2 PRs? One for removing 2FA and the other for displaying the key?

I think for the removing 2FA you might have to alter User#need_two_factor_authentication (https://github.com/alphagov/govwifi-admin/blob/364c146c7fea0ecce7469b3b07f5ceba3963c8f2/app/models/user.rb#L81) as well.

Could you also add a feature test demonstrating the change works as expected?

2021-07-23 09:58 UTC, colinbm commented
> Could you split this up into 2 PRs? One for removing 2FA and the other for displaying the key?

@koetsier How much do you want this? The key is a minor addition (bundled with design change), but I'll have to go back and redo the commits rather than cherry-pick to split them up.

2021-07-23 20:33 UTC, koetsier commented on spec/features/authentication/set_up_two_factor_authentication_spec.rb
> +    context "with a super admin user" do
maybe, now, we can make the default in line 6 a regular user and then set the user here to be a super user? That might make more sense now we don't have any special business logic for the super user anymore.

2021-07-23 20:33 UTC, koetsier approved these changes
I had one more comment but otherwise 👍 🥳

2021-07-26 09:41 UTC, merged