Improve edit password form
alphagov/govwifi-admin pull request #1550
Opened 2022-02-07 09:45 UTC by cbaines

### What
Improve error display on the change password form.

#### Before
![image](https://user-images.githubusercontent.com/1130010/152763884-bd21ab6c-3b3e-44ee-a9b1-bfba41712b57.png)

#### After
![image](https://user-images.githubusercontent.com/1130010/152763804-caded800-d5e8-4c08-9a5c-bc02c0a85c9b.png)

### Why
This makes the form easier to use.

Link to Trello card: https://trello.com/c/CwZ50yCx/1950-make-error-messages-produced-by-devise-gem-design-system-compliant

2022-02-07 14:38 UTC, koetsier commented
Looks good. Can you add some feature tests for this?

2022-02-08 09:52 UTC, koetsier requested changes
Could you add some tests for this?

2022-02-09 12:34 UTC, cbaines commented
> Looks good. Can you add some feature tests for this?

I've now extended the existing tests, and added some checks for the relevant CSS classes.

2022-02-09 12:41 UTC, koetsier approved these changes
Lgtm!

2022-02-09 15:26 UTC, merged