Gw 626 content design the 2 admin flow for new organisation
alphagov/govwifi-admin pull request #1901
Opened 2023-08-16 20:32 UTC by iram-shehzadi

### What
Introduce a new registration journey page that enables users to invite an additional admin member to their organisation. This enhancement also involves implementing error messages and restrictions on the IPs page, ensuring these measures remain in effect until a new admin is successfully added.

### Why
The motivation behind this development stems from the current limitation wherein some organisations are restricted to a single admin. This constraint poses significant challenges both for the affected organisations and the broader GovWifi initiative.

For instance:

Mitigating 2FA device challenges: Addressing situations where an admin loses access to their two-factor authentication (2FA) device is often a protracted process. Streamlining this procedure is vital for maintaining efficient admin operations.

Minimising impact of admin leaving: In scenarios where the sole admin leaves, the absence of a designated contact point can paralyse GovWifi operations, particularly during critical processes like certificate rotation.

Link to JIRA / Trello card (if applicable): 
https://technologyprogramme.atlassian.net/browse/GW-626

2023-08-17 13:15 UTC, A1Robson commented
So after some testing, it seems like it's still possible to add a location when there is only 1 administrator. This doesn't seem to be restricted in the same way as it is for an IP ?

2023-09-13 08:39 UTC, koetsier requested changes
Some changes. Let me know what you think

2023-09-13 08:39 UTC, koetsier commented on app/views/users/confirmations/invite_admin.html.erb
> +  <% if @errors %>
I don't think the `@errors` check is necessary if you instantiate a new User model in the invite_admin method.

2023-09-13 08:39 UTC, koetsier commented on app/views/users/confirmations/invite_admin.html.erb
> +        <%= hidden_field_tag :permission_level, "administrator" %>
Maybe better use the form model for the hidden field tags; ` <%= f.hidden_field :permission_level, value: "administrator" %>`

2023-09-13 08:39 UTC, koetsier commented on app/views/users/confirmations/invite_admin.html.erb
> +        <%= f.fields_for :user do |user_fields| %>
I don't think `fields_for` is necessary here. The resource should be a 'User' model

2023-09-13 08:39 UTC, koetsier commented on spec/features/locations/bulk_upload_spec.rb
> +      user.organisations.first.users.delete(another_administrator)
Would it not be better to not create the 'another_administrator'  in the first place?

2023-09-19 21:33 UTC, koetsier requested changes

2023-09-19 21:33 UTC, koetsier commented on app/controllers/users/invitations_controller.rb
> +      render(params[:user][:source] == "invite_admin" ? :invite_second_admin : :new)
I don't think there's a test for this yet.

2023-09-19 21:33 UTC, koetsier commented on app/views/layouts/application.html.erb
> +      <% if user_signed_in? && request.path != "/users/invitations/invite_second_admin" %>
Not too sure about this comparison with a specific URL. We could have a method like 'show_navigation_bars' or whatever in the application_controller and overload it as necessary in the right controller

2023-09-19 21:33 UTC, koetsier commented on spec/features/ips/add_ip_to_existing_location_spec.rb
> +      user.organisations.first.users.delete(another_administrator)
Might it be better not to add  the administrator in the first place?

2023-09-26 15:52 UTC, koetsier approved these changes
One comment 👍  

Can you sort out the commits before merging?

2023-09-26 15:52 UTC, koetsier commented on app/controllers/application_controller.rb
> +  def show_navigation_bars
I like this better, but there is this bit of logic in there that is very local to one controller. I think that, if you didn't know this was here, figuring out why the layout changes for this particular action would be really tricky.

I was thinking you could change this method back to:
```
def show_navigation_bars
  user_signed_in?
end
```
and then in the invitations controller you can overload this method:
```
  def show_navigation_bars
    return false if action_name=="invite_second_action"
    super
  end
```
That way, when you're looking at the `invite_second_admin` action, you can easily see why the navigation bars don't show.

What do you think?

2023-09-26 19:53 UTC, merged