Add filters to the team section
alphagov/govwifi-admin pull request #1946
Opened 2023-11-17 11:54 UTC by iram-shehzadi

### What

Add filters to the team section to show admin logs as we already collect this information however we don’t show it to super admins

### Why

It’d be useful to use when finding and contacting the most active admins for an organisation in certain instances - i.e. issues with that org, research, engagement, etc.

Link to JIRA / Trello card (if applicable):
https://technologyprogramme.atlassian.net/jira/software/projects/GW/boards/251?assignee=62c2bb48159944bf7687d333&selectedIssue=GW-791

2023-11-20 09:22 UTC, A1Robson commented on db/schema.rb
> +  create_table "active_storage_attachments", charset: "utf8mb3", force: :cascade do |t|
did you mean to change the charset?

2023-11-20 09:42 UTC, koetsier commented on app/controllers/super_admin/organisations_controller.rb
> +    @team = @organisation.users.order("#{sort_column} #{sort_direction}").order_by_name_and_email
does this work for email? the second scope seems to order for email again

2023-11-20 09:49 UTC, koetsier requested changes
Could you squash/reorder the commits and put a bit in the PR description?

2023-11-20 09:49 UTC, koetsier commented on app/controllers/super_admin/organisations_controller.rb
> +    @team = @organisation.users.order("#{sort_column} #{sort_direction}").order_by_name_and_email
does this work for the email field? the second scope seems to order for email again

2023-11-20 09:49 UTC, koetsier commented on spec/features/super_admin/locations/locations_spec.rb
> +      create(:user, name: "Team member 1", organisations: [organisation], last_sign_in_at: "10 Dec 2023")
maybe you could add a test for 'email' as well to show it works/does not work

2023-12-21 13:39 UTC, koetsier approved these changes
Looks good 🎄

2023-12-21 15:26 UTC, merged